const test=require('node:test');
const assert=require('node:assert/strict');
const SP=require('../assets/js/strategy-performance.js');
const D=SP.DAY;
function day(s){return Date.parse(s+'T00:00:00Z');}
function series(start,end,startValue,endValue,stepDays=1){const a=day(start),b=day(end),n=Math.floor((b-a)/(stepDays*D)),out=[];for(let i=0;i<=n;i++){const r=n?i/n:0;out.push({t:a+i*stepDays*D,v:startValue*Math.pow(endValue/startValue,r)});}if(out[out.length-1].t!==b)out.push({t:b,v:endValue});return out;}
function asset(ticker,start,end,growth=1){return {ticker,history:series(start,end,100,100*growth,7)};}
function weights(...pairs){return Object.fromEntries(pairs);}
const END='2026-09-11';

test('all assets with 10+ years history resolve 1Y/5Y/10Y',()=>{const r=SP.resolvePerformancePeriods([asset('A','2014-01-01',END,4),asset('B','2013-01-01',END,2)],weights(['A',.6],['B',.4]));assert.deepEqual(r.metrics.map(m=>m.label),['1Y','5Y','10Y']);});
test('one asset with only 6 years resolves 1Y/5Y/MAX',()=>{const r=SP.resolvePerformancePeriods([asset('A','2010-01-01',END,3),asset('B','2020-09-01',END,2)],weights(['A',.5],['B',.5]));assert.deepEqual(r.metrics.map(m=>m.label),['1Y','5Y','MAX']);assert.equal(r.commonRange.limitedByAsset,'B');});
test('one asset with about 1.8 years resolves 1Y/YTD/MAX',()=>{const assets=[asset('BTC','2015-01-01',END,5),asset('HYPE','2024-11-29',END,3),asset('XAUT','2020-01-01',END,2),asset('USDT','2018-01-01',END,1)],r=SP.resolvePerformancePeriods(assets,weights(['BTC',.5],['HYPE',.2],['XAUT',.15],['USDT',.15]));assert.deepEqual(r.metrics.map(m=>m.label),['1Y','YTD','MAX']);assert.equal(r.metrics[2].returnType,'cagr');assert.equal(r.commonRange.limitedByAsset,'HYPE');assert.match(r.metrics[2].tooltip,/HYPE/);});
test('less than one year uses a real trailing total-return period, never CAGR',()=>{const r=SP.resolvePerformancePeriods([asset('A','2026-02-01',END,1.4),asset('B','2026-02-01',END,1.1)],weights(['A',.5],['B',.5]));assert.ok(r.metrics.length>=1);assert.equal(r.metrics[0].returnType,'total_return');assert.equal(r.metrics[0].label,'6M');assert.equal(r.metrics.some(m=>m.returnType==='cagr'),false);});
test('newly launched token is not annualized',()=>{const r=SP.resolvePerformancePeriods([asset('OLD','2020-01-01',END,3),asset('NEW','2026-08-01',END,1.2)],weights(['OLD',.8],['NEW',.2]));assert.ok(r.metrics.every(m=>m.returnType==='total_return'));});
test('positive return remains positive',()=>{const r=SP.resolvePerformancePeriods([asset('A','2025-09-01',END,2)],weights(['A',1]));assert.ok(r.metrics[0].value>0);});
test('negative return remains negative',()=>{const r=SP.resolvePerformancePeriods([asset('A','2025-09-01',END,.5)],weights(['A',1]));assert.ok(r.metrics[0].value<0);});
test('exactly zero return remains exactly zero',()=>{const r=SP.resolvePerformancePeriods([asset('A','2025-09-01',END,1)],weights(['A',1]));assert.ok(Math.abs(r.metrics[0].value)<1e-12);});
test('missing historical data reports insufficient history',()=>{const r=SP.resolvePerformancePeriods([{ticker:'A',history:[]}],weights(['A',1]));assert.equal(r.error,'insufficient_history');assert.equal(r.metrics.length,0);});
test('asset inception during requested 5Y period prevents fake 5Y CAGR',()=>{const r=SP.resolvePerformancePeriods([asset('A','2010-01-01',END,3),asset('B','2023-01-01',END,2)],weights(['A',.7],['B',.3]));assert.equal(r.metrics.some(m=>m.label==='5Y'),false);assert.ok(r.metrics.some(m=>m.label==='MAX'));});
test('stablecoin actual price history participates normally',()=>{const r=SP.resolvePerformancePeriods([asset('RISK','2025-01-01',END,1.5),asset('USDT','2025-01-01',END,1.0002)],weights(['RISK',.5],['USDT',.5]));assert.ok(r.metrics[0].value>0);assert.equal(r.metrics[0].stablecoinFallbackUsed,false);});
test('percentage above 100% is preserved without clipping',()=>{const r=SP.resolvePerformancePeriods([{ticker:'A',history:series('2025-09-01',END,100,350,7)}],weights(['A',1]));assert.ok(r.metrics[0].value>1);});
test('CAGR uses portfolio final/initial value and actual elapsed years, not weighted asset CAGR',()=>{const start='2024-09-11',a={ticker:'A',history:series(start,END,100,400,7)},b={ticker:'B',history:series(start,END,100,100,7)},calc=SP.calculatePortfolioValueSeries([a,b],weights(['A',.5],['B',.5]),day(start),day(END)),c=SP.calculatePortfolioCAGR(calc),years=(c.endMs-c.startMs)/D/SP.YEAR_DAYS,expected=Math.pow(c.endValue/c.startValue,1/years)-1,weightedIndividual=.5*(Math.pow(4,1/years)-1);assert.equal(calc.initialValue,10000);assert.ok(Math.abs(c.value-expected)<1e-12);assert.ok(Math.abs(c.value-weightedIndividual)>1e-3);});
test('CAGR and total-return distinction is enforced at 365 days',()=>{const under=SP.calculatePortfolioCAGR([{t:day('2026-01-01'),v:10000},{t:day('2026-12-01'),v:11000}]),over=SP.calculatePortfolioCAGR([{t:day('2025-01-01'),v:10000},{t:day('2026-01-02'),v:11000}]);assert.equal(under,null);assert.ok(over&&Number.isFinite(over.value));});
test('stablecoin fallback is explicit and internally flagged',()=>{const f=SP.withStablecoinFallback({ticker:'USDT',isStablecoin:true,history:[]},day('2025-01-01'),day(END),true),r=SP.calculatePortfolioValueSeries([f],weights(['USDT',1]),day('2025-01-01'),day(END));assert.equal(f.stablecoinFallbackUsed,true);assert.equal(r.stablecoinFallbackUsed,true);});
test('declared asset inception can be older than the first returned observation',()=>{const a={ticker:'A',availableFrom:'2010-01-01T00:00:00Z',history:series('2016-09-12',END,100,200,30)},range=SP.getAssetAvailableRange(a);assert.equal(range.startDate.slice(0,10),'2010-01-01');});
